version: "3.3"
services:
  server:
    image: jvmtestsuite
    ports:
      - 8080
    environment:
      - JAVA_OPTS=-Xmx128m
      - JAVA_TOOL_OPTIONS=-javaagent:/tmp/jacocoagent.jar=destfile=/tmp/jacoco.exec,output=file
    volumes:
      - ./build/jacoco:/tmp

